repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.9
  hooks:
  # Run the linter.
  - id: ruff
    types_or: [python, pyi]
    args: [--fix]
  - id: ruff-format
    # Run the formatter.
    types_or: [python, pyi]
